import ContextProvider from "@/providers/ContextProvider";
import TanstackProvider from "@/providers/TanstackProvider";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import NavBar from "../Components/NavBar/NavBar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackProvider>
          <ContextProvider>
            <NavBar />
            <Toaster />
            <div className="mt-10 mx-10">{children}</div>
          </ContextProvider>
        </TanstackProvider>
      </body>
    </html>
  );
};

export default RootLayout;
