import { Inter } from "next/font/google";
import NavBar from "../Components/NavBar/NavBar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <div className="m-10">{children}</div>
      </body>
    </html>
  );
};

export default RootLayout;
