export const allRooms = [
  //! 1st Floor
  {
    _id: "ID001",
    name: "a1",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a1-sketch.png",
    floor: 1,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 2,
    beds: [
      {
        user: "",
        rent: { userRent: 3001, displayRent: 3001 },
        bookingCharge: 2001,
        bedNo: "a11",
        isBooked: false,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-a12",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a12",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID002",
    name: "a2",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a2-sketch.png",
    floor: 1,
    image: "/images/room/a2.jpeg",
    seats: 4,
    beds: [
      {
        user: "idOfUserOf-a21",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a21",
        isBooked: false,
        image: "/images/room/a21.jpeg",
      },
      {
        user: "idOfUserOf-a22",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a22",
        isBooked: false,
        image: "/images/room/a22.jpeg",
      },
      {
        user: "",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a23",
        isBooked: false,
        image: "/images/room/a23.jpeg",
      },
      {
        user: "idOfUserOf-a24",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a24",
        isBooked: false,
        image: "/images/room/a24.jpeg",
      },
    ],
  },
  {
    _id: "ID003",
    name: "a3",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a3-sketch.png",
    floor: 1,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 3,
    beds: [
      {
        user: "",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a31",
        isBooked: false,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "ssss",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a32",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a33",
        isBooked: false,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID004",
    name: "a4",
    block: "a",
    type: "wooden",
    sketch: "/images/sketch/a4-sketch.png",
    floor: 1,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 3,
    beds: [
      {
        user: "idOfUserOf-a41",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a41",
        isBooked: false,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-a42",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a42",
        isBooked: false,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-a43",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a43",
        isBooked: false,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID005",
    name: "a5",
    block: "a",
    type: "wooden",
    sketch: "/images/sketch/a5-sketch.png",
    floor: 1,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 1,
    beds: [
      {
        user: "idOfUserOf-a51",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 3000,
        bedNo: "a51",
        isBooked: false,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID006",
    name: "b1",
    block: "b",
    type: "concrete",
    sketch: "/images/sketch/b1-sketch.png",
    floor: 1,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 3,
    beds: [
      {
        user: "idOfUserOf-b11",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b11",
        isBooked: false,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-b12",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b12",
        isBooked: false,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b13",
        isBooked: false,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID007",
    name: "b2",
    block: "b",
    type: "concrete",
    sketch: "/images/sketch/b2-sketch.png",
    floor: 1,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 2,
    beds: [
      {
        user: "idOfUserOf-b21",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2222,
        bedNo: "b21",
        isBooked: false,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-b22",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2222,
        bedNo: "b22",
        isBooked: false,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID008",
    name: "b3",
    block: "b",
    type: "wooden",
    sketch: "/images/sketch/b3-sketch.png",
    floor: 1,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 2,
    beds: [
      {
        user: "idOfUserOf-b31",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 1111,
        bedNo: "b31",
        isBooked: false,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-b32",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 1111,
        bedNo: "b32",
        isBooked: false,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  //! 3rd Floor
  {
    _id: "ID009",
    name: "a1",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a1-sketch.png",
    floor: 3,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 2,
    beds: [
      {
        user: "idOfUserOf-a11",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a11",
        isBooked: false,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-a12",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a12",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID010",
    name: "a2",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a2-sketch.png",
    floor: 3,
    image: "/images/room/a2.jpeg",
    seats: 4,
    beds: [
      {
        user: "idOfUserOf-a21",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a21",
        isBooked: true,
        image: "/images/room/a21.jpeg",
      },
      {
        user: "idOfUserOf-a22",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a22",
        isBooked: true,
        image: "/images/room/a22.jpeg",
      },
      {
        user: "idOfUserOf-a23",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a23",
        isBooked: true,
        image: "/images/room/a23.jpeg",
      },
      {
        user: "idOfUserOf-a24",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a24",
        isBooked: true,
        image: "/images/room/a24.jpeg",
      },
    ],
  },
  {
    _id: "ID011",
    name: "a3",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a3-sketch.png",
    floor: 3,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 3,
    beds: [
      {
        user: "idOfUserOf-a31",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a31",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-a32",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a32",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-a32",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a33",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID012",
    name: "a4",
    block: "a",
    type: "wooden",
    sketch: "/images/sketch/a4-sketch.png",
    floor: 3,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 3,
    beds: [
      {
        user: "idOfUserOf-a41",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a41",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-a42",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a42",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-a43",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a43",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID013",
    name: "a5",
    block: "a",
    type: "wooden",
    sketch: "/images/sketch/a5-sketch.png",
    floor: 3,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 1,
    beds: [
      {
        user: "idOfUserOf-a51",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a51",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID014",
    name: "b1",
    block: "b",
    type: "concrete",
    sketch: "/images/sketch/b1-sketch.png",
    floor: 3,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 3,
    beds: [
      {
        user: "idOfUserOf-b11",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b11",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-b12",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b12",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b13",
        isBooked: false,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID015",
    name: "b2",
    block: "b",
    type: "concrete",
    sketch: "/images/sketch/b2-sketch.png",
    floor: 3,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 2,
    beds: [
      {
        user: "idOfUserOf-b21",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b21",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-b22",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b22",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID016",
    name: "b3",
    block: "b",
    type: "wooden",
    sketch: "/images/sketch/b3-sketch.png",
    floor: 3,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 2,
    beds: [
      {
        user: "idOfUserOf-b31",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b31",
        isBooked: false,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-b32",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b32",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  //! 4th Floor
  {
    _id: "ID017",
    name: "a1",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a1-sketch.png",
    floor: 4,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 2,
    beds: [
      {
        user: "idOfUserOf-a11",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a11",
        isBooked: false,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-a12",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a12",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID018",
    name: "a2",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a2-sketch.png",
    floor: 4,
    image: "/images/room/a2.jpeg",
    seats: 4,
    beds: [
      {
        user: "idOfUserOf-a21",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a21",
        isBooked: true,
        image: "/images/room/a21.jpeg",
      },
      {
        user: "idOfUserOf-a22",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a22",
        isBooked: true,
        image: "/images/room/a22.jpeg",
      },
      {
        user: "idOfUserOf-a23",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a23",
        isBooked: true,
        image: "/images/room/a23.jpeg",
      },
      {
        user: "idOfUserOf-a24",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a24",
        isBooked: true,
        image: "/images/room/a24.jpeg",
      },
    ],
  },
  {
    _id: "ID019",
    name: "a3",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a3-sketch.png",
    floor: 4,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 3,
    beds: [
      {
        user: "idOfUserOf-a31",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a31",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-a32",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a32",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-a32",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a33",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID020",
    name: "a4",
    block: "a",
    type: "wooden",
    sketch: "/images/sketch/a4-sketch.png",
    floor: 4,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 3,
    beds: [
      {
        user: "idOfUserOf-a41",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a41",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-a42",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a42",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-a43",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a43",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID021",
    name: "a5",
    block: "a",
    type: "wooden",
    sketch: "/images/sketch/a5-sketch.png",
    floor: 4,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 1,
    beds: [
      {
        user: "idOfUserOf-a51",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a51",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID022",
    name: "b1",
    block: "b",
    type: "concrete",
    sketch: "/images/sketch/b1-sketch.png",
    floor: 4,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 3,
    beds: [
      {
        user: "idOfUserOf-b11",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b11",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-b12",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b12",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b13",
        isBooked: false,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID023",
    name: "b2",
    block: "b",
    type: "concrete",
    sketch: "/images/sketch/b2-sketch.png",
    floor: 4,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 2,
    beds: [
      {
        user: "idOfUserOf-b21",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b21",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-b22",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b22",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID024",
    name: "b3",
    block: "b",
    type: "wooden",
    sketch: "/images/sketch/b3-sketch.png",
    floor: 4,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 2,
    beds: [
      {
        user: "idOfUserOf-b31",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b31",
        isBooked: false,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-b32",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b32",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  //! 6th Floor
  {
    _id: "ID025",
    name: "a1",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a1-sketch.png",
    floor: 6,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 2,
    beds: [
      {
        user: "idOfUserOf-a11",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a11",
        isBooked: false,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-a12",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a12",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID026",
    name: "a2",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a2-sketch.png",
    floor: 6,
    image: "/images/room/a2.jpeg",
    seats: 4,
    beds: [
      {
        user: "idOfUserOf-a21",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a21",
        isBooked: true,
        image: "/images/room/a21.jpeg",
      },
      {
        user: "idOfUserOf-a22",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a22",
        isBooked: true,
        image: "/images/room/a22.jpeg",
      },
      {
        user: "idOfUserOf-a23",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a23",
        isBooked: true,
        image: "/images/room/a23.jpeg",
      },
      {
        user: "idOfUserOf-a24",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a24",
        isBooked: true,
        image: "/images/room/a24.jpeg",
      },
    ],
  },
  {
    _id: "ID027",
    name: "a3",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a3-sketch.png",
    floor: 6,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 3,
    beds: [
      {
        user: "idOfUserOf-a31",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a31",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-a32",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a32",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-a32",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a33",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID028",
    name: "a4",
    block: "a",
    type: "wooden",
    sketch: "/images/sketch/a4-sketch.png",
    floor: 6,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 3,
    beds: [
      {
        user: "idOfUserOf-a41",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a41",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-a42",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a42",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-a43",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a43",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID029",
    name: "a5",
    block: "a",
    type: "wooden",
    sketch: "/images/sketch/a5-sketch.png",
    floor: 6,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 1,
    beds: [
      {
        user: "idOfUserOf-a51",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a51",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID030",
    name: "b1",
    block: "b",
    type: "concrete",
    sketch: "/images/sketch/b1-sketch.png",
    floor: 6,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 3,
    beds: [
      {
        user: "idOfUserOf-b11",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b11",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-b12",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b12",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b13",
        isBooked: false,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID031",
    name: "b2",
    block: "b",
    type: "concrete",
    sketch: "/images/sketch/b2-sketch.png",
    floor: 6,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 2,
    beds: [
      {
        user: "idOfUserOf-b21",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b21",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-b22",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b22",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID032",
    name: "b3",
    block: "b",
    type: "wooden",
    sketch: "/images/sketch/b3-sketch.png",
    floor: 6,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 2,
    beds: [
      {
        user: "idOfUserOf-b31",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b31",
        isBooked: false,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-b32",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b32",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  //! 7th Floor
  {
    _id: "ID033",
    name: "a1",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a1-sketch.png",
    floor: 7,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 2,
    beds: [
      {
        user: "idOfUserOf-a11",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a11",
        isBooked: false,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-a12",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a12",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID034",
    name: "a2",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a2-sketch.png",
    floor: 7,
    image: "/images/room/a2.jpeg",
    seats: 4,
    beds: [
      {
        user: "idOfUserOf-a21",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a21",
        isBooked: true,
        image: "/images/room/a21.jpeg",
      },
      {
        user: "idOfUserOf-a22",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a22",
        isBooked: true,
        image: "/images/room/a22.jpeg",
      },
      {
        user: "idOfUserOf-a23",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a23",
        isBooked: true,
        image: "/images/room/a23.jpeg",
      },
      {
        user: "idOfUserOf-a24",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a24",
        isBooked: true,
        image: "/images/room/a24.jpeg",
      },
    ],
  },
  {
    _id: "ID035",
    name: "a3",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a3-sketch.png",
    floor: 7,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 3,
    beds: [
      {
        user: "idOfUserOf-a31",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a31",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-a32",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a32",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-a32",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a33",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID036",
    name: "a4",
    block: "a",
    type: "wooden",
    sketch: "/images/sketch/a4-sketch.png",
    floor: 7,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 3,
    beds: [
      {
        user: "idOfUserOf-a41",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a41",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-a42",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a42",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-a43",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a43",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID037",
    name: "a5",
    block: "a",
    type: "wooden",
    sketch: "/images/sketch/a5-sketch.png",
    floor: 7,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 1,
    beds: [
      {
        user: "idOfUserOf-a51",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "a51",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID038",
    name: "b1",
    block: "b",
    type: "concrete",
    sketch: "/images/sketch/b1-sketch.png",
    floor: 7,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 3,
    beds: [
      {
        user: "idOfUserOf-b11",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b11",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-b12",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b12",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b13",
        isBooked: false,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID039",
    name: "b2",
    block: "b",
    type: "concrete",
    sketch: "/images/sketch/b2-sketch.png",
    floor: 7,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 2,
    beds: [
      {
        user: "idOfUserOf-b21",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b21",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-b22",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b22",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
  {
    _id: "ID040",
    name: "b3",
    block: "b",
    type: "wooden",
    sketch: "/images/sketch/b3-sketch.png",
    floor: 7,
    image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
    seats: 2,
    beds: [
      {
        user: "idOfUserOf-b31",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b31",
        isBooked: false,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
      {
        user: "idOfUserOf-b32",
        rent: { userRent: 3000, displayRent: 3000 },
        bookingCharge: 2000,
        bedNo: "b32",
        isBooked: true,
        image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
      },
    ],
  },
];
