export const allRoomss = [
  //! 1st Floor
  // {
  //   _id: "ID001",
  //   name: "a1",
  //   video: "https://www.youtube.com/embed/pT8LyeET7OE?si=jH0-x1qAO1V83Kp9",
  //   block: "a",
  //   type: "concrete",
  //   sketch: "/images/sketch/a1-sketch.png",
  //   floor: 1,
  //   image: "/images/room/a1.jpeg",
  //   seats: 2,
  //   toilet: { type: "attached", image: "/images/room/a1at.jpeg" },
  //   balcony: { state: true, image: "/images/room/a1b.jpeg" },
  //   beds: [
  //     {
  //       user: "",
  //       rent: { userRent: 3001, displayRent: 3001 },
  //       bookingCharge: 2001,
  //       bedNo: "a11",
  //       isBooked: false,
  //       image: "/images/room/a11.jpeg",
  //     },
  //     {
  //       user: "idOfUserOf-a12",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a12",
  //       isBooked: true,
  //       image: "/images/room/a12.jpeg",
  //     },
  //   ],
  // },
  // {
  //   _id: "ID002",
  //   name: "a2",
  //   video: "https://www.youtube.com/embed/0J6PI8LyA5Y?si=M3rN24hIUtVy9MAA",
  //   block: "a",
  //   type: "concrete",
  //   sketch: "/images/sketch/a2-sketch.png",
  //   floor: 1,
  //   image: "/images/room/a2.jpeg",
  //   seats: 4,
  //   toilet: { type: "attached", image: "/images/room/a2at.jpeg" },
  //   balcony: { state: true, image: "/images/room/a2b.jpeg" },
  //   beds: [
  //     {
  //       user: "idOfUserOf-a21",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a21",
  //       isBooked: false,
  //       image: "/images/room/a21.jpeg",
  //     },
  //     {
  //       user: "idOfUserOf-a22",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a22",
  //       isBooked: false,
  //       image: "/images/room/a22.jpeg",
  //     },
  //     {
  //       user: "",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a23",
  //       isBooked: false,
  //       image: "/images/room/a23.jpeg",
  //     },
  //     {
  //       user: "idOfUserOf-a24",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a24",
  //       isBooked: false,
  //       image: "/images/room/a24.jpeg",
  //     },
  //   ],
  // },
  // {
  //   _id: "ID003",
  //   name: "a3",
  //   video: "https://www.youtube.com/embed/6IqhrJ8ZNMM?si=a40H2Q2-lSrBCfAt",
  //   block: "a",
  //   type: "concrete",
  //   sketch: "/images/sketch/a3-sketch.png",
  //   floor: 1,
  //   image: "/images/room/a3.jpeg",
  //   seats: 3,
  //   toilet: { type: "attached", image: "/images/room/a3at.jpeg" },
  //   balcony: { state: true, image: "/images/room/a3b.jpeg" },
  //   beds: [
  //     {
  //       user: "",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a31",
  //       isBooked: false,
  //       image: "/images/room/a31.jpeg",
  //     },
  //     {
  //       user: "ssss",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a32",
  //       isBooked: true,
  //       image: "/images/room/a32.jpeg",
  //     },
  //     {
  //       user: "",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a33",
  //       isBooked: false,
  //       image: "/images/room/a33.jpeg",
  //     },
  //   ],
  // },
  // {
  //   _id: "ID004",
  //   name: "a4",
  //   video:"https://www.youtube.com/embed/0J6PI8LyA5Y?si=M3rN24hIUtVy9MAA",
  //   block: "a",
  //   type: "wooden",
  //   sketch: "/images/sketch/a4-sketch.png",
  //   floor: 1,
  //   image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //   seats: 3,
  //   toilet:{type:"attached",image:"/images/room/"},
  //   balcony:{state:"true",image:"/images/room/"}//   ,
  //   beds: [
  //     {
  //       user: "idOfUserOf-a41",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a41",
  //       isBooked: false,
  //       image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //     },
  //     {
  //       user: "idOfUserOf-a42",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a42",
  //       isBooked: false,
  //       image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //     },
  //     {
  //       user: "idOfUserOf-a43",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a43",
  //       isBooked: false,
  //       image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //     },
  //   ],
  // },
  // {
  //   _id: "ID005",
  //   name: "a5",
  //   video:"https://www.youtube.com/embed/0J6PI8LyA5Y?si=M3rN24hIUtVy9MAA",
  //   block: "a",
  //   type: "wooden",
  //   sketch: "/images/sketch/a5-sketch.png",
  //   floor: 1,
  //   image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //   seats: 1,
  //   toilet:{type:"attached",image:"/images/room/"},
  //   balcony:{state:"true",image:"/images/room/"}//   ,
  //   beds: [
  //     {
  //       user: "idOfUserOf-a51",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 3000,
  //       bedNo: "a51",
  //       isBooked: false,
  //       image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //     },
  //   ],
  // },
  // {
  //   _id: "ID006",
  //   name: "b1",
  //   video: "https://www.youtube.com/embed/VdCCt_c_q8s?si=9HYCi2dwHsdgtqo3",
  //   block: "b",
  //   type: "concrete",
  //   sketch: "/images/sketch/b1-sketch.png",
  //   floor: 1,
  //   image: "/images/room/b1.jpeg",
  //   seats: 3,
  //   toilet: { type: "common", image: "/images/room/a3at.jpeg" },
  //   balcony: { state: true, image: "/images/room/b1b.jpeg" },
  //   beds: [
  //     {
  //       user: "idOfUserOf-b11",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "b11",
  //       isBooked: false,
  //       image: "/images/room/b11.jpeg",
  //     },
  //     {
  //       user: "idOfUserOf-b12",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "b12",
  //       isBooked: false,
  //       image: "/images/room/b12.jpeg",
  //     },
  //     {
  //       user: "",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "b13",
  //       isBooked: false,
  //       image: "/images/room/b13.jpeg",
  //     },
  //   ],
  // },
  // {
  //   _id: "ID007",
  //   name: "b2",
  //   video: "https://www.youtube.com/embed/apDcNAXa0jA?si=9P1fIqAvWpCLGl0W",
  //   block: "b",
  //   type: "concrete",
  //   sketch: "/images/sketch/b2-sketch.png",
  //   floor: 1,
  //   image: "/images/room/b2.jpeg",
  //   seats: 2,
  //   toilet: { type: "attached", image: "/images/room/b2at.jpeg" },
  //   balcony: { state: true, image: "/images/room/b2b.jpeg" },
  //   beds: [
  //     {
  //       user: "idOfUserOf-b21",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2222,
  //       bedNo: "b21",
  //       isBooked: false,
  //       image: "/images/room/b21.jpeg",
  //     },
  //     {
  //       user: "idOfUserOf-b22",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2222,
  //       bedNo: "b22",
  //       isBooked: false,
  //       image: "/images/room/b22.jpeg",
  //     },
  //   ],
  // },
  // {
  //   _id: "ID008",
  //   name: "b3",
  //   video: "https://www.youtube.com/embed/tC8amRV2g3M?si=YgQ7UWGLO7HjrOsK",
  //   block: "b",
  //   type: "wooden",
  //   sketch: "/images/sketch/b3-sketch.png",
  //   floor: 1,
  //   image: "/images/room/b3.jpeg",
  //   seats: 2,
  //   toilet: { type: "common", image: "/images/room/a3at.jpeg" },
  //   balcony: { state: false, image: "" },
  //   beds: [
  //     {
  //       user: "idOfUserOf-b31",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 1111,
  //       bedNo: "b31",
  //       isBooked: false,
  //       image: "/images/room/b31.jpeg",
  //     },
  //     {
  //       user: "idOfUserOf-b32",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 1111,
  //       bedNo: "b32",
  //       isBooked: false,
  //       image: "/images/room/b32.jpeg",
  //     },
  //   ],
  // },
  //! 3rd Floor
  {
    _id: "ID009",
    name: "a1",
    video: "https://www.youtube.com/embed/pT8LyeET7OE?si=jH0-x1qAO1V83Kp9",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a1-sketch.png",
    floor: 3,
    image: "/images/room/a1.jpeg",
    seats: 2,
    toilet: { type: "attached", image: "/images/room/a1at.jpeg" },
    balcony: { state: true, image: "/images/room/a1b.jpeg" },
    beds: [
      {
        user: "idOfUserOf-a11",
        rent: { userRent: 4000, displayRent: 4500 },
        bookingCharge: 1000,
        bedNo: "a11",
        isBooked: true,
        image: "/images/room/a11.jpeg",
      },
      {
        user: "idOfUserOf-a12",
        rent: { userRent: 4000, displayRent: 4500 },
        bookingCharge: 1000,
        bedNo: "a12",
        isBooked: true,
        image: "/images/room/a12.jpeg",
      },
    ],
  },
  {
    _id: "ID010",
    name: "a2",
    video: "https://www.youtube.com/embed/0J6PI8LyA5Y?si=M3rN24hIUtVy9MAA",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a2-sketch.png",
    floor: 3,
    image: "/images/room/a2.jpeg",
    seats: 4,
    toilet: { type: "attached", image: "/images/room/a2at.jpeg" },
    balcony: { state: true, image: "/images/room/a2b.jpeg" },
    beds: [
      {
        user: "idOfUserOf-a21",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a21",
        isBooked: false,
        image: "/images/room/a21.jpeg",
      },
      {
        user: "idOfUserOf-a22",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a22",
        isBooked: false,
        image: "/images/room/a22.jpeg",
      },
      {
        user: "idOfUserOf-a23",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a23",
        isBooked: false,
        image: "/images/room/a23.jpeg",
      },
      {
        user: "idOfUserOf-a24",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a24",
        isBooked: false,
        image: "/images/room/a24.jpeg",
      },
    ],
  },
  {
    _id: "ID011",
    name: "a3",
    video: "https://www.youtube.com/embed/6IqhrJ8ZNMM?si=a40H2Q2-lSrBCfAt",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a3-sketch.png",
    floor: 3,
    image: "/images/room/a3.jpeg",
    seats: 3,
    toilet: { type: "attached", image: "/images/room/a3at.jpeg" },
    balcony: { state: true, image: "/images/room/a3b.jpeg" },
    beds: [
      {
        user: "idOfUserOf-a31",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a31",
        isBooked: true,
        image: "/images/room/a31.jpeg",
      },
      {
        user: "idOfUserOf-a32",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a32",
        isBooked: true,
        image: "/images/room/a32.jpeg",
      },
      {
        user: "idOfUserOf-a32",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a33",
        isBooked: true,
        image: "/images/room/a33.jpeg",
      },
    ],
  },
  // {
  //   _id: "ID012",
  //   name: "a4",
  //   video:"https://www.youtube.com/embed/0J6PI8LyA5Y?si=M3rN24hIUtVy9MAA",
  //   block: "a",
  //   type: "wooden",
  //   sketch: "/images/sketch/a4-sketch.png",
  //   floor: 3,
  //   image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //   seats: 3,
  //   toilet:{type:"attached",image:"/images/room/"},
  //   balcony:{state:"true",image:"/images/room/"}//   ,
  //   beds: [
  //     {
  //       user: "idOfUserOf-a41",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a41",
  //       isBooked: true,
  //       image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //     },
  //     {
  //       user: "idOfUserOf-a42",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a42",
  //       isBooked: true,
  //       image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //     },
  //     {
  //       user: "idOfUserOf-a43",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a43",
  //       isBooked: true,
  //       image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //     },
  //   ],
  // },
  // {
  //   _id: "ID013",
  //   name: "a5",
  //   video:"https://www.youtube.com/embed/0J6PI8LyA5Y?si=M3rN24hIUtVy9MAA",
  //   block: "a",
  //   type: "wooden",
  //   sketch: "/images/sketch/a5-sketch.png",
  //   floor: 3,
  //   image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //   seats: 1,
  //   toilet:{type:"attached",image:"/images/room/"},
  //   balcony:{state:"true",image:"/images/room/"}//   ,
  //   beds: [
  //     {
  //       user: "idOfUserOf-a51",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a51",
  //       isBooked: true,
  //       image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //     },
  //   ],
  // },
  {
    _id: "ID014",
    name: "b1",
    video: "https://www.youtube.com/embed/VdCCt_c_q8s?si=9HYCi2dwHsdgtqo3",
    block: "b",
    type: "concrete",
    sketch: "/images/sketch/b1-sketch.png",
    floor: 3,
    image: "/images/room/b1.jpeg",
    seats: 3,
    toilet: { type: "common", image: "/images/room/a3at.jpeg" },
    balcony: { state: true, image: "/images/room/b1b.jpeg" },
    beds: [
      {
        user: "idOfUserOf-b11",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "b11",
        isBooked: true,
        image: "/images/room/b11.jpeg",
      },
      {
        user: "idOfUserOf-b12",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "b12",
        isBooked: true,
        image: "/images/room/b12.jpeg",
      },
      {
        user: "",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "b13",
        isBooked: true,
        image: "/images/room/b13.jpeg",
      },
    ],
  },
  {
    _id: "ID015",
    name: "b2",
    video: "https://www.youtube.com/embed/apDcNAXa0jA?si=9P1fIqAvWpCLGl0W",
    block: "b",
    type: "concrete",
    sketch: "/images/sketch/b2-sketch.png",
    floor: 3,
    image: "/images/room/b2.jpeg",
    seats: 2,
    toilet: { type: "attached", image: "/images/room/b2at.jpeg" },
    balcony: { state: true, image: "/images/room/b2b.jpeg" },
    beds: [
      {
        user: "idOfUserOf-b21",
        rent: { userRent: 4000, displayRent: 4000 },
        bookingCharge: 1000,
        bedNo: "b21",
        isBooked: true,
        image: "/images/room/b21.jpeg",
      },
      {
        user: "idOfUserOf-b22",
        rent: { userRent: 4000, displayRent: 4000 },
        bookingCharge: 1000,
        bedNo: "b22",
        isBooked: true,
        image: "/images/room/b22.jpeg",
      },
    ],
  },
  {
    _id: "ID016",
    name: "b3",
    video: "https://www.youtube.com/embed/tC8amRV2g3M?si=YgQ7UWGLO7HjrOsK",
    block: "b",
    type: "wooden",
    sketch: "/images/sketch/b3-sketch.png",
    floor: 3,
    image: "/images/room/b3.jpeg",
    seats: 2,
    toilet: { type: "common", image: "/images/room/a3at.jpeg" },
    balcony: { state: false, image: "" },
    beds: [
      {
        user: "idOfUserOf-b31",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "b31",
        isBooked: false,
        image: "/images/room/b31.jpeg",
      },
      {
        user: "idOfUserOf-b32",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "b32",
        isBooked: false,
        image: "/images/room/b32.jpeg",
      },
    ],
  },
  //! 4th Floor
  {
    _id: "ID017",
    name: "a1",
    video: "https://www.youtube.com/embed/pT8LyeET7OE?si=jH0-x1qAO1V83Kp9",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a1-sketch.png",
    floor: 4,
    image: "/images/room/a1.jpeg",
    seats: 2,
    toilet: { type: "attached", image: "/images/room/a1at.jpeg" },
    balcony: { state: true, image: "/images/room/a1b.jpeg" },
    beds: [
      {
        user: "idOfUserOf-a11",
        rent: { userRent: 4500, displayRent: 4500 },
        bookingCharge: 1000,
        bedNo: "a11",
        isBooked: true,
        image: "/images/room/a11.jpeg",
      },
      {
        user: "idOfUserOf-a12",
        rent: { userRent: 4500, displayRent: 4500 },
        bookingCharge: 1000,
        bedNo: "a12",
        isBooked: true,
        image: "/images/room/a12.jpeg",
      },
    ],
  },
  {
    _id: "ID018",
    name: "a2",
    video: "https://www.youtube.com/embed/0J6PI8LyA5Y?si=M3rN24hIUtVy9MAA",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a2-sketch.png",
    floor: 4,
    image: "/images/room/a2.jpeg",
    seats: 4,
    toilet: { type: "attached", image: "/images/room/a2at.jpeg" },
    balcony: { state: true, image: "/images/room/a2b.jpeg" },
    beds: [
      {
        user: "idOfUserOf-a21",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a21",
        isBooked: true,
        image: "/images/room/a21.jpeg",
      },
      {
        user: "idOfUserOf-a22",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a22",
        isBooked: true,
        image: "/images/room/a22.jpeg",
      },
      {
        user: "idOfUserOf-a23",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a23",
        isBooked: true,
        image: "/images/room/a23.jpeg",
      },
      {
        user: "idOfUserOf-a24",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a24",
        isBooked: true,
        image: "/images/room/a24.jpeg",
      },
    ],
  },
  {
    _id: "ID019",
    name: "a3",
    video: "https://www.youtube.com/embed/6IqhrJ8ZNMM?si=a40H2Q2-lSrBCfAt",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a3-sketch.png",
    floor: 4,
    image: "/images/room/a3.jpeg",
    seats: 3,
    toilet: { type: "attached", image: "/images/room/a3at.jpeg" },
    balcony: { state: true, image: "/images/room/a3b.jpeg" },
    beds: [
      {
        user: "idOfUserOf-a31",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a31",
        isBooked: true,
        image: "/images/room/a31.jpeg",
      },
      {
        user: "idOfUserOf-a32",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a32",
        isBooked: true,
        image: "/images/room/a32.jpeg",
      },
      {
        user: "idOfUserOf-a32",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a33",
        isBooked: true,
        image: "/images/room/a33.jpeg",
      },
    ],
  },
  // {
  //   _id: "ID020",
  //   name: "a4",
  //   video:"https://www.youtube.com/embed/0J6PI8LyA5Y?si=M3rN24hIUtVy9MAA",
  //   block: "a",
  //   type: "wooden",
  //   sketch: "/images/sketch/a4-sketch.png",
  //   floor: 4,
  //   image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //   seats: 3,
  //   toilet:{type:"attached",image:"/images/room/"},
  //   balcony:{state:"true",image:"/images/room/"}//   ,
  //   beds: [
  //     {
  //       user: "idOfUserOf-a41",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a41",
  //       isBooked: true,
  //       image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //     },
  //     {
  //       user: "idOfUserOf-a42",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a42",
  //       isBooked: true,
  //       image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //     },
  //     {
  //       user: "idOfUserOf-a43",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a43",
  //       isBooked: true,
  //       image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //     },
  //   ],
  // },
  // {
  //   _id: "ID021",
  //   name: "a5",
  //   video:"https://www.youtube.com/embed/0J6PI8LyA5Y?si=M3rN24hIUtVy9MAA",
  //   block: "a",
  //   type: "wooden",
  //   sketch: "/images/sketch/a5-sketch.png",
  //   floor: 4,
  //   image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //   seats: 1,
  //   toilet:{type:"attached",image:"/images/room/"},
  //   balcony:{state:"true",image:"/images/room/"}//   ,
  //   beds: [
  //     {
  //       user: "idOfUserOf-a51",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a51",
  //       isBooked: true,
  //       image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //     },
  //   ],
  // },
  {
    _id: "ID022",
    name: "b1",
    video: "https://www.youtube.com/embed/VdCCt_c_q8s?si=9HYCi2dwHsdgtqo3",
    block: "b",
    type: "concrete",
    sketch: "/images/sketch/b1-sketch.png",
    floor: 4,
    image: "/images/room/b1.jpeg",
    seats: 3,
    toilet: { type: "common", image: "/images/room/a3at.jpeg" },
    balcony: { state: true, image: "/images/room/b1b.jpeg" },
    beds: [
      {
        user: "idOfUserOf-b11",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "b11",
        isBooked: false,
        image: "/images/room/b11.jpeg",
      },
      {
        user: "idOfUserOf-b12",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "b12",
        isBooked: false,
        image: "/images/room/b12.jpeg",
      },
      {
        user: "",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "b13",
        isBooked: true,
        image: "/images/room/b13.jpeg",
      },
    ],
  },
  {
    _id: "ID023",
    name: "b2",
    video: "https://www.youtube.com/embed/apDcNAXa0jA?si=9P1fIqAvWpCLGl0W",
    block: "b",
    type: "concrete",
    sketch: "/images/sketch/b2-sketch.png",
    floor: 4,
    image: "/images/room/b2.jpeg",
    seats: 2,
    toilet: { type: "attached", image: "/images/room/b2at.jpeg" },
    balcony: { state: true, image: "/images/room/b2b.jpeg" },
    beds: [
      {
        user: "idOfUserOf-b21",
        rent: { userRent: 4000, displayRent: 4000 },
        bookingCharge: 1000,
        bedNo: "b21",
        isBooked: true,
        image: "/images/room/b21.jpeg",
      },
      {
        user: "idOfUserOf-b22",
        rent: { userRent: 4000, displayRent: 4000 },
        bookingCharge: 1000,
        bedNo: "b22",
        isBooked: true,
        image: "/images/room/b22.jpeg",
      },
    ],
  },
  {
    _id: "ID024",
    name: "b3",
    video: "https://www.youtube.com/embed/tC8amRV2g3M?si=YgQ7UWGLO7HjrOsK",
    block: "b",
    type: "wooden",
    sketch: "/images/sketch/b3-sketch.png",
    floor: 4,
    image: "/images/room/b3.jpeg",
    seats: 2,
    toilet: { type: "common", image: "/images/room/a3at.jpeg" },
    balcony: { state: false, image: "" },
    beds: [
      {
        user: "idOfUserOf-b31",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "b31",
        isBooked: true,
        image: "/images/room/b31.jpeg",
      },
      {
        user: "idOfUserOf-b32",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "b32",
        isBooked: true,
        image: "/images/room/b32.jpeg",
      },
    ],
  },
  //! 6th Floor
  {
    _id: "ID025",
    name: "a1",
    video: "https://www.youtube.com/embed/pT8LyeET7OE?si=jH0-x1qAO1V83Kp9",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a1-sketch.png",
    floor: 6,
    image: "/images/room/a1.jpeg",
    seats: 2,
    toilet: { type: "attached", image: "/images/room/a1at.jpeg" },
    balcony: { state: true, image: "/images/room/a1b.jpeg" },
    beds: [
      {
        user: "idOfUserOf-a11",
        rent: { userRent: 4000, displayRent: 4500 },
        bookingCharge: 1000,
        bedNo: "a11",
        isBooked: true,
        image: "/images/room/a11.jpeg",
      },
      {
        user: "idOfUserOf-a12",
        rent: { userRent: 4000, displayRent: 4500 },
        bookingCharge: 1000,
        bedNo: "a12",
        isBooked: true,
        image: "/images/room/a12.jpeg",
      },
    ],
  },
  {
    _id: "ID026",
    name: "a2",
    video: "https://www.youtube.com/embed/0J6PI8LyA5Y?si=M3rN24hIUtVy9MAA",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a2-sketch.png",
    floor: 6,
    image: "/images/room/a2.jpeg",
    seats: 4,
    toilet: { type: "attached", image: "/images/room/a2at.jpeg" },
    balcony: { state: true, image: "/images/room/a2b.jpeg" },
    beds: [
      {
        user: "idOfUserOf-a21",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a21",
        isBooked: false,
        image: "/images/room/a21.jpeg",
      },
      {
        user: "idOfUserOf-a22",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a22",
        isBooked: false,
        image: "/images/room/a22.jpeg",
      },
      {
        user: "idOfUserOf-a23",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a23",
        isBooked: false,
        image: "/images/room/a23.jpeg",
      },
      {
        user: "idOfUserOf-a24",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a24",
        isBooked: false,
        image: "/images/room/a24.jpeg",
      },
    ],
  },
  {
    _id: "ID027",
    name: "a3",
    video: "https://www.youtube.com/embed/6IqhrJ8ZNMM?si=a40H2Q2-lSrBCfAt",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a3-sketch.png",
    floor: 6,
    image: "/images/room/a3.jpeg",
    seats: 3,
    toilet: { type: "attached", image: "/images/room/a3at.jpeg" },
    balcony: { state: true, image: "/images/room/a3b.jpeg" },
    beds: [
      {
        user: "idOfUserOf-a31",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a31",
        isBooked: true,
        image: "/images/room/a31.jpeg",
      },
      {
        user: "idOfUserOf-a32",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a32",
        isBooked: false,
        image: "/images/room/a32.jpeg",
      },
      {
        user: "idOfUserOf-a32",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a33",
        isBooked: true,
        image: "/images/room/a33.jpeg",
      },
    ],
  },
  // {
  //   _id: "ID028",
  //   name: "a4",
  //   video:"https://www.youtube.com/embed/0J6PI8LyA5Y?si=M3rN24hIUtVy9MAA",
  //   block: "a",
  //   type: "wooden",
  //   sketch: "/images/sketch/a4-sketch.png",
  //   floor: 6,
  //   image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //   seats: 3,
  //   toilet:{type:"attached",image:"/images/room/"},
  //   balcony:{state:"true",image:"/images/room/"}//   ,
  //   beds: [
  //     {
  //       user: "idOfUserOf-a41",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a41",
  //       isBooked: true,
  //       image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //     },
  //     {
  //       user: "idOfUserOf-a42",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a42",
  //       isBooked: true,
  //       image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //     },
  //     {
  //       user: "idOfUserOf-a43",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a43",
  //       isBooked: true,
  //       image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //     },
  //   ],
  // },
  // {
  //   _id: "ID029",
  //   name: "a5",
  //   video:"https://www.youtube.com/embed/0J6PI8LyA5Y?si=M3rN24hIUtVy9MAA",
  //   block: "a",
  //   type: "wooden",
  //   sketch: "/images/sketch/a5-sketch.png",
  //   floor: 6,
  //   image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //   seats: 1,
  //   toilet:{type:"attached",image:"/images/room/"},
  //   balcony:{state:"true",image:"/images/room/"}//   ,
  //   beds: [
  //     {
  //       user: "idOfUserOf-a51",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a51",
  //       isBooked: true,
  //       image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //     },
  //   ],
  // },
  {
    _id: "ID030",
    name: "b1",
    video: "https://www.youtube.com/embed/VdCCt_c_q8s?si=9HYCi2dwHsdgtqo3",
    block: "b",
    type: "concrete",
    sketch: "/images/sketch/b1-sketch.png",
    floor: 6,
    image: "/images/room/b1.jpeg",
    seats: 3,
    toilet: { type: "common", image: "/images/room/a3at.jpeg" },
    balcony: { state: true, image: "/images/room/b1b.jpeg" },
    beds: [
      {
        user: "idOfUserOf-b11",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "b11",
        isBooked: true,
        image: "/images/room/b11.jpeg",
      },
      {
        user: "idOfUserOf-b12",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "b12",
        isBooked: false,
        image: "/images/room/b12.jpeg",
      },
      {
        user: "",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "b13",
        isBooked: false,
        image: "/images/room/b13.jpeg",
      },
    ],
  },
  {
    _id: "ID031",
    name: "b2",
    video: "https://www.youtube.com/embed/apDcNAXa0jA?si=9P1fIqAvWpCLGl0W",
    block: "b",
    type: "concrete",
    sketch: "/images/sketch/b2-sketch.png",
    floor: 6,
    image: "/images/room/b2.jpeg",
    seats: 2,
    toilet: { type: "attached", image: "/images/room/b2at.jpeg" },
    balcony: { state: true, image: "/images/room/b2b.jpeg" },
    beds: [
      {
        user: "idOfUserOf-b21",
        rent: { userRent: 4000, displayRent: 4000 },
        bookingCharge: 1000,
        bedNo: "b21",
        isBooked: true,
        image: "/images/room/b21.jpeg",
      },
      {
        user: "idOfUserOf-b22",
        rent: { userRent: 4000, displayRent: 4000 },
        bookingCharge: 1000,
        bedNo: "b22",
        isBooked: true,
        image: "/images/room/b22.jpeg",
      },
    ],
  },
  {
    _id: "ID032",
    name: "b3",
    video: "https://www.youtube.com/embed/tC8amRV2g3M?si=YgQ7UWGLO7HjrOsK",
    block: "b",
    type: "wooden",
    sketch: "/images/sketch/b3-sketch.png",
    floor: 6,
    image: "/images/room/b3.jpeg",
    seats: 2,
    toilet: { type: "common", image: "/images/room/a3at.jpeg" },
    balcony: { state: false, image: "" },
    beds: [
      {
        user: "idOfUserOf-b31",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "b31",
        isBooked: true,
        image: "/images/room/b31.jpeg",
      },
      {
        user: "idOfUserOf-b32",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "b32",
        isBooked: true,
        image: "/images/room/b32.jpeg",
      },
    ],
  },
  //! 7th Floor
  {
    _id: "ID033",
    name: "a1",
    video: "https://www.youtube.com/embed/pT8LyeET7OE?si=jH0-x1qAO1V83Kp9",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a1-sketch.png",
    floor: 7,
    image: "/images/room/a1.jpeg",
    seats: 2,
    toilet: { type: "attached", image: "/images/room/a1at.jpeg" },
    balcony: { state: true, image: "/images/room/a1b.jpeg" },
    beds: [
      {
        user: "idOfUserOf-a11",
        rent: { userRent: 4500, displayRent: 4500 },
        bookingCharge: 1000,
        bedNo: "a11",
        isBooked: false,
        image: "/images/room/a11.jpeg",
      },
      {
        user: "idOfUserOf-a12",
        rent: { userRent: 4500, displayRent: 4500 },
        bookingCharge: 1000,
        bedNo: "a12",
        isBooked: false,
        image: "/images/room/a12.jpeg",
      },
    ],
  },
  {
    _id: "ID034",
    name: "a2",
    video: "https://www.youtube.com/embed/0J6PI8LyA5Y?si=M3rN24hIUtVy9MAA",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a2-sketch.png",
    floor: 7,
    image: "/images/room/a2.jpeg",
    seats: 4,
    toilet: { type: "attached", image: "/images/room/a2at.jpeg" },
    balcony: { state: true, image: "/images/room/a2b.jpeg" },
    beds: [
      {
        user: "idOfUserOf-a21",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a21",
        isBooked: true,
        image: "/images/room/a21.jpeg",
      },
      {
        user: "idOfUserOf-a22",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a22",
        isBooked: true,
        image: "/images/room/a22.jpeg",
      },
      {
        user: "idOfUserOf-a23",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a23",
        isBooked: true,
        image: "/images/room/a23.jpeg",
      },
      {
        user: "idOfUserOf-a24",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a24",
        isBooked: true,
        image: "/images/room/a24.jpeg",
      },
    ],
  },
  {
    _id: "ID035",
    name: "a3",
    video: "https://www.youtube.com/embed/6IqhrJ8ZNMM?si=a40H2Q2-lSrBCfAt",
    block: "a",
    type: "concrete",
    sketch: "/images/sketch/a3-sketch.png",
    floor: 7,
    image: "/images/room/a3.jpeg",
    seats: 3,
    toilet: { type: "attached", image: "/images/room/a3at.jpeg" },
    balcony: { state: true, image: "/images/room/a3b.jpeg" },
    beds: [
      {
        user: "idOfUserOf-a31",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a31",
        isBooked: false,
        image: "/images/room/a31.jpeg",
      },
      {
        user: "idOfUserOf-a32",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a32",
        isBooked: true,
        image: "/images/room/a32.jpeg",
      },
      {
        user: "idOfUserOf-a32",
        rent: { userRent: 0, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "a33",
        isBooked: true,
        image: "/images/room/a33.jpeg",
      },
    ],
  },
  // {
  //   _id: "ID036",
  //   name: "a4",
  //   video:"https://www.youtube.com/embed/0J6PI8LyA5Y?si=M3rN24hIUtVy9MAA",
  //   block: "a",
  //   type: "wooden",
  //   sketch: "/images/sketch/a4-sketch.png",
  //   floor: 7,
  //   image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //   seats: 3,
  //   toilet:{type:"attached",image:"/images/room/"},
  //   balcony:{state:"true",image:"/images/room/"}//   ,
  //   beds: [
  //     {
  //       user: "idOfUserOf-a41",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a41",
  //       isBooked: true,
  //       image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //     },
  //     {
  //       user: "idOfUserOf-a42",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a42",
  //       isBooked: true,
  //       image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //     },
  //     {
  //       user: "idOfUserOf-a43",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a43",
  //       isBooked: true,
  //       image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //     },
  //   ],
  // },
  // {
  //   _id: "ID037",
  //   name: "a5",
  //   video:"https://www.youtube.com/embed/0J6PI8LyA5Y?si=M3rN24hIUtVy9MAA",
  //   block: "a",
  //   type: "wooden",
  //   sketch: "/images/sketch/a5-sketch.png",
  //   floor: 7,
  //   image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //   seats: 1,
  //   toilet:{type:"attached",image:"/images/room/"},
  //   balcony:{state:"true",image:"/images/room/"}//   ,
  //   beds: [
  //     {
  //       user: "idOfUserOf-a51",
  //       rent: { userRent: 3000, displayRent: 3000 },
  //       bookingCharge: 2000,
  //       bedNo: "a51",
  //       isBooked: true,
  //       image: "https://i.ibb.co/Lgj3BHG/main-Image.jpg",
  //     },
  //   ],
  // },
  {
    _id: "ID038",
    name: "b1",
    video: "https://www.youtube.com/embed/VdCCt_c_q8s?si=9HYCi2dwHsdgtqo3",
    block: "b",
    type: "concrete",
    sketch: "/images/sketch/b1-sketch.png",
    floor: 7,
    image: "/images/room/b1.jpeg",
    seats: 3,
    toilet: { type: "common", image: "/images/room/a3at.jpeg" },
    balcony: { state: true, image: "/images/room/b1b.jpeg" },
    beds: [
      {
        user: "idOfUserOf-b11",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "b11",
        isBooked: false,
        image: "/images/room/b11.jpeg",
      },
      {
        user: "idOfUserOf-b12",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "b12",
        isBooked: false,
        image: "/images/room/b12.jpeg",
      },
      {
        user: "",
        rent: { userRent: 3500, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "b13",
        isBooked: false,
        image: "/images/room/b13.jpeg",
      },
    ],
  },
  {
    _id: "ID039",
    name: "b2",
    video: "https://www.youtube.com/embed/apDcNAXa0jA?si=9P1fIqAvWpCLGl0W",
    block: "b",
    type: "concrete",
    sketch: "/images/sketch/b2-sketch.png",
    floor: 7,
    image: "/images/room/b2.jpeg",
    seats: 2,
    toilet: { type: "attached", image: "/images/room/b2at.jpeg" },
    balcony: { state: true, image: "/images/room/b2b.jpeg" },
    beds: [
      {
        user: "idOfUserOf-b21",
        rent: { userRent: 3500, displayRent: 4000 },
        bookingCharge: 1000,
        bedNo: "b21",
        isBooked: true,
        image: "/images/room/b21.jpeg",
      },
      {
        user: "idOfUserOf-b22",
        rent: { userRent: 3500, displayRent: 4000 },
        bookingCharge: 1000,
        bedNo: "b22",
        isBooked: true,
        image: "/images/room/b22.jpeg",
      },
    ],
  },
  {
    _id: "ID040",
    name: "b3",
    video: "https://www.youtube.com/embed/tC8amRV2g3M?si=YgQ7UWGLO7HjrOsK",
    block: "b",
    type: "wooden",
    sketch: "/images/sketch/b3-sketch.png",
    floor: 7,
    image: "/images/room/b3.jpeg",
    seats: 2,
    toilet: { type: "common", image: "/images/room/a3at.jpeg" },
    balcony: { state: false, image: "" },
    beds: [
      {
        user: "idOfUserOf-b31",
        rent: { userRent: 3000, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "b31",
        isBooked: true,
        image: "/images/room/b31.jpeg",
      },
      {
        user: "idOfUserOf-b32",
        rent: { userRent: 3000, displayRent: 3500 },
        bookingCharge: 1000,
        bedNo: "b32",
        isBooked: true,
        image: "/images/room/b32.jpeg",
      },
    ],
  },
];

export const roomStructure = [
  {
    name: "a1",
    beds: ["a11", "a12"],
  },
  {
    name: "a2",
    beds: ["a21", "a22", "a23", "a24"],
  },
  {
    name: "a3",
    beds: ["a31", "a32", "a33"],
  },
  {
    name: "a4",
    beds: ["a41", "a42", "a43"],
  },
  {
    name: "a5",
    beds: ["a51"],
  },
  {
    name: "a6",
    beds: ["a61"],
  },
  {
    name: "b1",
    beds: ["b11", "b12", "b13"],
  },
  {
    name: "b2",
    beds: ["b21", "b22"],
  },
  {
    name: "b3",
    beds: ["b31", "b32"],
  },
  {
    name: "b4",
    beds: ["b41"],
  },
];
